export const SET_ACTIVE_GAMES = 'SET_ACTIVE_GAMES';
export const SET_CURRENT_GAME = 'SET_CURRENT_GAME';
export const SET_GAME_ROUNDS  = 'SET_GAME_ROUNDS';
export const ADD_POSTED_SCORE = 'ADD_POSTED_SCORE';
