asyncapi: '2.6.0'
info:
  title: Spicy Golf API
  version: '4.0.0'
  description: |
    The Spicy Golf API allows mobile and web apps to interact with Spicy Golf data and events
servers:
  dev:
    url: ws://localhost:3000/
    protocol: ws

channels:
  /:
    publish:
      description: Send messages to the API
      operationId: processReceivedMessage
      message:
        oneOf:
          - $ref : '#/components/messages/ping'

    subscribe:
      description: Messages that you receive from the API
      operationId: sendMessage
      message:
        oneOf:
          - $ref: '#/components/messages/pong'

components:
  messages:
    ping:
      name: ping
      summary: Ping server to determine whether connection is alive
      payload:
        $ref: '#/components/schemas/ping'
      x-response:
        $ref: '#/components/schemas/pong'

    pong:
      summary: Pong is a response to ping message
      description: Server pong response to a ping to determine whether connection is alive. This is an application level pong as opposed to default pong in websockets standard which is sent by client in response to a ping
      payload:
        $ref: '#/components/schemas/pong'

  schemas:
    ping:
      type: object
      properties:
        event:
          type: string
          const: ping
          description: game uuid from client
        reqid:
          $ref: '#/components/schemas/reqid'
      required:
        - event

    pong:
      type: object
      properties:
        event:
          type: string
          const: pong
        reqid:
          $ref: '#/components/schemas/reqid'

    reqid:
      type: string
      description: client originated ID reflected in response message.
